#pragma once

#include <algorithm>
#include <cmath>
#include <functional>
#include <initializer_list>
#include <iostream>
#include <memory>
#include <nlohmann/json.hpp>
#include <numeric>
#include <optional>
#include <random>
#include <stdexcept>
#include <string>
#include <tuple>
#include <type_traits>
#include <unordered_set>
#include <variant>
#include <vector>
#include <type_traits>
#include <cmath>
#include <chrono>
#include <unordered_map>

using nlohmann::json;
using std::accumulate;
using std::copy;
using std::cosh;
using std::dynamic_pointer_cast;
using std::equal;
using std::exp;
using std::initializer_list;
using std::invalid_argument;
using std::log;
using std::logic_error;
using std::make_shared;
using std::make_unique;
using std::move;
using std::multiplies;
using std::nullopt;
using std::optional;
using std::ostream;
using std::out_of_range;
using std::remove_reference_t;
using std::runtime_error;
using std::shared_ptr;
using std::string;
using std::tanh;
using std::unique_ptr;
using std::unordered_set;
using std::variant;
using std::vector;
using std::visit;
using std::function;

using uli = unsigned long int;
