#pragma once

#include <memory>
#include <nlohmann/json.hpp>
#include <numeric>
#include <stdexcept>
#include <string>
#include <vector>
#include <variant>
#include <unordered_set>
#include <optional>
#include <iostream>

using nlohmann::json;
using std::accumulate;
using std::initializer_list;
using std::logic_error;
using std::make_shared;
using std::make_unique;
using std::move;
using std::multiplies;
using std::out_of_range;
using std::shared_ptr;
using std::string;
using std::unique_ptr;
using std::vector;
using std::tanh;
using std::cosh;
using std::log;
using std::variant;
using std::unordered_set;
using std::runtime_error;
using std::optional;
using std::visit;
using std::ostream;
using std::remove_reference_t;
